### ISSUE TITLE
[DOC] Create index page for API docs

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/pyjanitor#245] opened 2019-05-07 14:15 UTC
`pandas` API docs have an index of functions: https://pandas.pydata.org/pandas-docs/stable/reference/general_functions.html

We probably should have something like this.

**Comment by ricky-lim** [comment] 2019-05-07 19:00
I'm working on this ...

**Comment by NapsterInBlue** [comment] 2019-05-07 19:20
Ah, whoops. My issue was a duplicate of this.

Body of the issue might be useful, though!

#264

**Comment by jack-kessler-88** [comment] 2019-05-07 21:49
I made a branch that experiments with changing the doc structure so we have and index page that gives summaries of chemistry, finance, functions etc submodules with links to a page per submodule. It should be pretty simple to modify it to fit any future changes in how we want to document the functions

**Closed** 2019-05-07 22:22 UTC
Labels: being worked on, docfix, good intermediate issue
