### ISSUE TITLE
ConfigParser import error

### ISSUE THREAD

**Issue by anzelpwj** [ericmjl/pyjanitor#696] opened 2020-07-06 17:48 UTC
# Brief Description

@preetida found that she tried to import PyJanitor for the Bayesian tutorial, the code would not load and it noted an import error for ConfigParser. This is unusual, as CP is part of the standard library, but something to look in to.

<img width="562" alt="Screen Shot 2020-07-06 at 1 17 01 PM" src="https://user-images.githubusercontent.com/4054130/86623265-e400c500-bf86-11ea-833e-5966dcef0488.png">

I'll ask Preetida to fill in any relevant information.

# System Information

- Operating system: macOS/Linux/Windows  
- OS details (optional):  
- Python version (required):

# Minimally Reproducible Code

# Error Messages

```
ModuleNotFoundError: No module named ConfigParser
```

**Comment by anzelpwj** [comment] 2020-07-06 17:52
My understanding is this was an error with a pip intall, but the error did not present itself with a conda install.

**Comment by hectormz** [comment] 2020-07-08 23:20
Hi @anzelpwj, I think that the user was accidentally `pip` installing `janitor` instead of `pyjanitor`, which looks like it was built for Python 2 (where `ConfigParser` exists instead of `configparser` now in Python 3). That seems to be confirmed with the mention of `Flask` etc

**Comment by ericmjl** [comment] 2020-07-09 00:33
It is indeed confusing - the package name is pyjanitor, but the import name is janitor. My bad, everybody, I should have just stuck with conventions and picked pyjanitor as the import name.

**Comment by hectormz** [comment] 2020-07-16 20:45
@ericmjl is there anything we should do with this issue, or close it?

**Comment by ericmjl** [comment] 2020-07-16 23:43
Closing it out, thanks for the reminder, @hectormz!

**Closed by ericmjl** 2020-07-16 23:43 UTC
Labels: triage
